name: Multi-Platform CTest Routine

on:
  push:
    branches: [development, stable]

jobs:
  build-and-test:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug]
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Configure CMake
      run: >
        cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DTENGINE_BUILD_NOTES:STRING="Compiled with machine love"

    - name: Build Engine
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

    - name: Run GTest 
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ matrix.build_type }} --extra-verbose